version: '3'

services:
  app:
    image: nooocaaaa/logisticsproject:latest
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_LINK=jdbc:postgresql://db:5432/logistics
      - DATABASE_USER=noelia
      - DATABASE_PASSWORD=nocavi12

  db:
    image: postgres
    environment:
      - POSTGRES_DB=logistics
      - POSTGRES_USER=noelia
      - POSTGRES_PASSWORD=nocavi12
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
